name: CI

on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Docker build & push
        uses: docker/build-push-action@v1
        with:
          registry: rg.fr-par.scw.cloud/yabab
          username: nologin
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: uvue-examples
          tags: latest
